{
 "title": "Chain-main",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "targets",
    "query": "label_values(tendermint_consensus_height,instance)"
   },
   { "name": "validator" }
  ]
 },
 "panels": [
  {
   "title": "Average Block Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(tendermint_consensus_block_interval_seconds_sum[1m])/rate(tendermint_consensus_block_interval_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Height",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(tendermint_consensus_height{instance=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Weight Online",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(tendermint_consensus_validators_power{instance=~\"$targets\"})"
    }
   ]
  },
  {
   "title": "Byzantine Weight",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(tendermint_consensus_byzantine_validators_power)"
    }
   ]
  },
  {
   "title": "Byzantine validators",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(tendermint_consensus_byzantine_validators)"
    }
   ]
  },
  {
   "title": "Missing validators",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(tendermint_consensus_missing_validators{instance=~\"$targets\"})",
     "rawSql": "SELECT\n  height AS \"time\",\n  address AS metric,\n  height AS \"height\"\nFROM miss_infos\nWHERE\n  address = '183B82E026DFDD8F0633A375D60F066480156908'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Missed blocks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "Select",
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  address AS metric,\n  height AS \"height\"\nFROM miss_infos\nWHERE\n  $__timeFilter(\"time\") AND\n  address = '$validator'\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Block times",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(tendermint_consensus_block_interval_seconds_bucket[1m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "avg(histogram_quantile(0.95, rate(tendermint_consensus_block_interval_seconds_bucket[1m])))",
     "legendFormat": "95th"
    },
    {
     "expr": "avg(histogram_quantile(0.50, rate(tendermint_consensus_block_interval_seconds_bucket[1m])))",
     "legendFormat": "50th"
    },
    {
     "expr": "avg(histogram_quantile(0.10, rate(tendermint_consensus_block_interval_seconds_bucket[1m])))",
     "legendFormat": "10th"
    },
    {
     "expr": "avg(rate(tendermint_consensus_block_interval_seconds_sum[1m])/rate(tendermint_consensus_block_interval_seconds_count[1m]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Heights",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_height{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Missed blocks",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT t.height,t.time, t.alerted FROM public.miss_infos t\n      Where address = '$validator' ORDER by height DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Last Proposals",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT t.height,t.title,t.proposal_status,t.alerted FROM public.proposals t\n      ORDER by height DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Rounds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_rounds{instance=~\"$targets\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Number of peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_p2p_peers{instance=~\"$targets\"}"
    }
   ]
  },
  {
   "title": "Outbound peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  count(id) AS \"outbound\",\n  node AS \"node\"\nFROM peer_infos\nWHERE\n  $__timeFilter(\"timestamp\")\n  and is_outbound = TRUE\nGROUP BY timestamp, node\nORDER BY 1"
    }
   ]
  }
 ]
}